'use strict';
const express=require('express'),crypto=require('crypto');const {requireAuth,verifyCsrf}=require('../lib/middleware');const {db}=require('../lib/db');const router=express.Router();router.use(requireAuth);
const MODES={images:{name:'Imagenes',sceneSeconds:6,imageShare:1,videoShare:0,base:4},hybrid:{name:'Hibrido',sceneSeconds:6,imageShare:.8,videoShare:.2,base:8},animated:{name:'Animado',sceneSeconds:6,imageShare:0,videoShare:1,base:18}};
const STYLES=['documental','misterio','terror','historia','negocios','filosofia','ciencia','emocional'];
function calc(minutes,mode){minutes=Math.min(120,Math.max(1,Number(minutes)||10));const m=MODES[mode]||MODES.images,scenes=Math.ceil(minutes*60/m.sceneSeconds),images=Math.ceil(scenes*m.imageShare),clips=scenes-images,voice=Math.ceil(minutes*1.2);return {minutes,scenes,images,animatedClips:clips,voiceCredits:voice,credits:Math.ceil(m.base+images*.22+clips*2.4+voice),mode,name:m.name}}
router.post('/estimate',(req,res)=>res.json({ok:true,estimate:calc(req.body&&req.body.minutes,String(req.body&&req.body.mode||'images'))}));
router.get('/presets',(req,res)=>res.json({ok:true,modes:MODES,styles:STYLES}));
router.get('/projects',(req,res)=>res.json({ok:true,projects:db.prepare('SELECT id,title,style,mode,target_minutes,estimated_credits,status,created_at FROM video_projects WHERE user_id=? ORDER BY created_at DESC').all(req.session.userId)}));
router.get('/projects/:id',(req,res)=>{const p=db.prepare('SELECT * FROM video_projects WHERE id=? AND user_id=?').get(req.params.id,req.session.userId);if(!p)return res.status(404).json({ok:false,error:'Proyecto no encontrado'});res.json({ok:true,project:p,scenes:db.prepare('SELECT * FROM video_scenes WHERE project_id=? ORDER BY scene_no').all(p.id)})});
router.post('/projects',verifyCsrf,(req,res)=>{try{const idea=String(req.body&&req.body.idea||'').trim(),style=String(req.body&&req.body.style||'documental'),mode=String(req.body&&req.body.mode||'images');if(idea.length<10)return res.status(400).json({ok:false,error:'La idea o guion es demasiado corto.'});if(!STYLES.includes(style)||!MODES[mode])return res.status(400).json({ok:false,error:'Configuracion invalida.'});const e=calc(req.body.minutes,mode),id=crypto.randomUUID(),title=idea.split(/[.!?\n]/)[0].slice(0,100)||'Nuevo video';db.prepare('INSERT INTO video_projects(id,user_id,title,idea,style,mode,target_minutes,scene_seconds,estimated_credits) VALUES(?,?,?,?,?,?,?,?,?)').run(id,req.session.userId,title,idea,style,mode,e.minutes,MODES[mode].sceneSeconds,e.credits);const insert=db.prepare('INSERT INTO video_scenes(project_id,scene_no,kind,duration_seconds,narration,visual_prompt) VALUES(?,?,?,?,?,?)');const tx=db.transaction(()=>{for(let i=1;i<=e.scenes;i++){const animated=mode==='animated'||(mode==='hybrid'&&i%5===0);insert.run(id,i,animated?'video':'image',MODES[mode].sceneSeconds,'','')}});tx();res.json({ok:true,projectId:id,estimate:e});}catch(err){res.status(400).json({ok:false,error:err.message})}});
router.patch('/projects/:id/scenes/:scene',verifyCsrf,(req,res)=>{const p=db.prepare('SELECT id FROM video_projects WHERE id=? AND user_id=?').get(req.params.id,req.session.userId);if(!p)return res.status(404).json({ok:false,error:'Proyecto no encontrado'});const allowed=['narration','visual_prompt','kind'];const sets=[],vals=[];for(const k of allowed)if(req.body&&req.body[k]!=null){if(k==='kind'&&!['image','video'].includes(req.body[k]))continue;sets.push(k+'=?');vals.push(String(req.body[k]).slice(0,5000))}if(!sets.length)return res.status(400).json({ok:false,error:'Sin cambios'});vals.push(req.params.id,Number(req.params.scene));db.prepare('UPDATE video_scenes SET '+sets.join(',')+' WHERE project_id=? AND scene_no=?').run(...vals);res.json({ok:true})});
module.exports=router;