'use strict';
const express=require('express');
const crypto=require('crypto');
const config=require('../lib/config');
const {txPayment}=require('../lib/saas-db');
const router=express.Router();
function eq(a,b){const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&x.length>0&&crypto.timingSafeEqual(x,y)}
function hmac(secret,text){return crypto.createHmac('sha256',secret).update(text).digest('hex')}
function normalized(body,provider){const m=body&&body.data&&body.data.object?body.data.object:body||{};const meta=m.metadata||body.metadata||{};return {provider,event_id:String(body.id||m.id||''),event_type:String(body.type||body.action||''),provider_ref:String(m.payment_intent||m.id||body.data&&body.data.id||''),user_id:Number(meta.user_id||body.user_id),plan_code:String(meta.plan_code||body.plan_code||''),amount_microusd:Number(meta.amount_microusd||body.amount_microusd||0),fee_microusd:Number(meta.fee_microusd||body.fee_microusd||0),currency:String(m.currency||body.currency||'USD').toUpperCase(),status:String(meta.status||body.status||'paid'),payload_hash:crypto.createHash('sha256').update(JSON.stringify(body||{})).digest('hex')}}
router.post('/stripe',(req,res)=>{try{if(!config.stripeWebhookSecret)return res.status(503).json({ok:false,error:'Stripe no configurado.'});const sig=String(req.get('stripe-signature')||'');const provided=(sig.match(/v1=([^,]+)/)||[])[1];const timestamp=(sig.match(/t=([^,]+)/)||[])[1];const raw=JSON.stringify(req.body||{});if(!timestamp||!provided||!eq(hmac(config.stripeWebhookSecret,timestamp+'.'+raw),provided))return res.status(401).json({ok:false,error:'Firma invalida.'});const p=normalized(req.body,'stripe');if(!p.event_id||!p.user_id||!p.plan_code)return res.status(400).json({ok:false,error:'Evento incompleto.'});res.json({ok:true,result:txPayment(p)});}catch(e){res.status(400).json({ok:false,error:e.message});}});
router.post('/mercadopago',(req,res)=>{try{if(!config.mercadoPagoWebhookSecret)return res.status(503).json({ok:false,error:'Mercado Pago no configurado.'});const sig=String(req.get('x-signature')||'');const requestId=String(req.get('x-request-id')||'');const eventId=String(req.query['data.id']||req.body&&req.body.data&&req.body.data.id||'');const ts=(sig.match(/ts=([^,;]+)/)||[])[1],provided=(sig.match(/v1=([^,;]+)/)||[])[1];const manifest='id:'+eventId+';request-id:'+requestId+';ts:'+ts+';';if(!ts||!provided||!eq(hmac(config.mercadoPagoWebhookSecret,manifest),provided))return res.status(401).json({ok:false,error:'Firma invalida.'});const p=normalized(req.body,'mercadopago');p.event_id=String(req.body&&req.body.id||eventId);if(!p.event_id||!p.user_id||!p.plan_code)return res.status(400).json({ok:false,error:'Evento incompleto.'});res.json({ok:true,result:txPayment(p)});}catch(e){res.status(400).json({ok:false,error:e.message});}});
module.exports=router;